# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dfl.communication.grpc import communication_pb2 as dfl_dot_communication_dot_grpc_dot_communication__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dfl/communication/grpc/communication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handle = channel.unary_unary(
                '/Communicator/Handle',
                request_serializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HandleSubscribe = channel.unary_unary(
                '/Communicator/HandleSubscribe',
                request_serializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Subscribe.SerializeToString,
                response_deserializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.FromString,
                _registered_method=True)
        self.HandleReceive = channel.unary_unary(
                '/Communicator/HandleReceive',
                request_serializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Receive.SerializeToString,
                response_deserializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.FromString,
                _registered_method=True)


class CommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Handle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleSubscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleReceive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handle': grpc.unary_unary_rpc_method_handler(
                    servicer.Handle,
                    request_deserializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HandleSubscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleSubscribe,
                    request_deserializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Subscribe.FromString,
                    response_serializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.SerializeToString,
            ),
            'HandleReceive': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleReceive,
                    request_deserializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Receive.FromString,
                    response_serializer=dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Communicator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Communicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Communicator/Handle',
            dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleSubscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Communicator/HandleSubscribe',
            dfl_dot_communication_dot_grpc_dot_communication__pb2.Subscribe.SerializeToString,
            dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HandleReceive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Communicator/HandleReceive',
            dfl_dot_communication_dot_grpc_dot_communication__pb2.Receive.SerializeToString,
            dfl_dot_communication_dot_grpc_dot_communication__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
