# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfl/communication/grpc/communication.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'dfl/communication/grpc/communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*dfl/communication/grpc/communication.proto\x1a\x1bgoogle/protobuf/empty.proto\"N\n\x07Message\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x07.HeaderH\x00\x88\x01\x01\x12\x11\n\x04\x62ody\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x42\t\n\x07_headerB\x07\n\x05_body\"\x1d\n\x06Header\x12\x13\n\x0bjson_string\x18\x01 \x01(\t\"M\n\tSubscribe\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x14\n\x0cwait_publish\x18\x02 \x01(\x08\x12\x11\n\tmeta_only\x18\x03 \x01(\x08\"E\n\x07Receive\x12\x1c\n\x06header\x18\x01 \x01(\x0b\x32\x07.HeaderH\x00\x88\x01\x01\x12\x11\n\tmeta_only\x18\x02 \x01(\x08\x42\t\n\x07_header2\x88\x01\n\x0c\x43ommunicator\x12*\n\x06Handle\x12\x08.Message\x1a\x16.google.protobuf.Empty\x12\'\n\x0fHandleSubscribe\x12\n.Subscribe\x1a\x08.Message\x12#\n\rHandleReceive\x12\x08.Receive\x1a\x08.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfl.communication.grpc.communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=75
  _globals['_MESSAGE']._serialized_end=153
  _globals['_HEADER']._serialized_start=155
  _globals['_HEADER']._serialized_end=184
  _globals['_SUBSCRIBE']._serialized_start=186
  _globals['_SUBSCRIBE']._serialized_end=263
  _globals['_RECEIVE']._serialized_start=265
  _globals['_RECEIVE']._serialized_end=334
  _globals['_COMMUNICATOR']._serialized_start=337
  _globals['_COMMUNICATOR']._serialized_end=473
# @@protoc_insertion_point(module_scope)
